name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make proc_stat
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with: 
          path: proc_stat
          name: proc_stat
